### ISSUE TITLE
Long-Term Plan to Migrate to a New Schema

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify-data-warehouse#12]
Here's a rough outline on how this can be broken into phases with stable intermediates.  I expect this to be revised many times.

This can be a parent ticket, pointing to the implementation for every of the following:
1. [schema migration to create additional field to store 2 alleles per result](https://github.com/cbmi/varify-data-warehouse/pull/2)
2. [data migration to duplicate het alt variants](https://github.com/cbmi/varify-data-warehouse/issues/17)
   1. alter Variant model properties to rely on genotype lexicon for determining which if either of the two alleles is the reference allele: this applies to the read depth properties as well
   2. example: 'AG,AGTA,CAGATA' in the alt field would be represented by 3 Variant records
3. data migration to improve genotype lexicon: this would simply involve importing a fixture on top of the existing lexicon
   1. '0/1', '1/2', '1/#' notation doesn't mean anything in the database, and can be simplified
4. data migration to store deletions using an encoded integer
   1. alter Variant model properties to generate ref and alt as though they were from a VCF file
5. addition of 2bit-encoded sequence for genome assembly
6. schema migration to remove ref property of Variant
   1. alter Variant model properties to perform ref sequence lookup when necessary
7. schema migration to refactor Variant model to Allele model
8. schema migration to add lookup table to link Results to Alleles
9. data migration to populate lookup table of Results to Alleles (reverse would populate foreign key pair)
10. schema migration to remove Allele foreign key pair from Result model
11. schema migration to add Event table
12. data migration to populate Event table, based on unique locations of variants
13. add support for reference intervals to importer

**Comment by naegelyd** [comment]
Applies to closed PRs and discontinued work. Will reopen later if this is considered necessary.
