### ISSUE TITLE
Add accessor to retrieve tuple of alleles from a Result

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify-data-warehouse#15]
As of now, the Result class has a variant property that is deprecated.  [PR 2](https://github.com/cbmi/varify-data-warehouse/pull/2) adds an accessor for legacy support, but this should be phased out.

A new accessor should be added that returns a tuple of alleles for a Result object.  There should be no assumption that it be limited to two alleles, although through most of the schema transition there shall be such a limit.

Similarly, an accessor for a tuple of allelic depth values should be made available.

**Comment by naegelyd** [comment]
Applies to closed PRs and discontinued work. Will reopen later if this is considered necessary.
