### ISSUE TITLE
Add static genome version setting, remove from SampleRun, Genome

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/varify-data-warehouse#23]
Currently the genome is only referenced on [SampleRun](https://github.com/cbmi/varify-data-warehouse/blob/master/vdw/samples/models.py#L304) which is a bit far removed from the two primary models: Variant and Sample.

@leipzig any concerns/suggestions with this change? It was driven by [this comment](https://github.com/cbmi/varify/pull/384#issuecomment-58953721)

**Comment by naegelyd** [comment]
@bruth I talked with @leipzig and it seems like there is no strong demand for supporting multiple genomes. Currently, we just use a single genome internally so it seems wasteful to me to slap a FK on every variant and sample. 

I propose removing SampleRun and Genome altogether and just using a project setting `GENOME`. When `GENOME` is set, the MANIFEST and/or the VCF file will be verified to make sure it is using the correct genome version. If it does not match the project setting, the sample will not be loaded. If the `GENOME` setting is not set, then we will not do this verification. It just seems to me that we would want to limit our data to single genome.

Thoughts? I'm fine taking the option of supporting multiple genomes but it just seems to me it would be much more consistent to support a single genome and only load data that matches that representation.

**Comment by bruth** [comment]
I presume since we do not have any other facility in Varify for differentiating genomes then this would be ok (e.g. annotations). I am cognizant of external users who may need to load samples using separate genomes, however since the variant table is pending a refactor it may be best to explicitly support only version (hard-coded in settings).

When/if the time comes that we use hg20, I think the better approach would be to stand up a separate VDW since majority, if not all, of the data will be affected.

**Comment by penningtonj** [comment]
At some point there will be a new genome build and we will migrate to it.  At that point (if we're still warehousing variants) we'll want to be able to differentiate between the two.  Jer is the best person to think this through.

**Comment by bruth** [comment]
@penningtonj Yep. We confirmed with @leipzig before making this decision.

**Comment by bruth** [comment]
@leipzig What can be used to reliability check/confirm which genome is being used? I see the `reference` in the VCF format, but that appears to vary depending the file used.

**Comment by naegelyd** [comment]
I talked to Juan and he said that he will add the genome to the script generating the MANIFEST. So, it will be something like:

```
[genome]
name = ...
version = ...
```

**Comment by bruth** [comment]
Great.

**Comment by naegelyd** [comment]
Resolved in #29.
