### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'

### ISSUE THREAD

**Issue by leipzig** [chop-dbhi/varify-data-warehouse#33]
is this attribute missing from global_settings?

**Comment by naegelyd** [comment]
Can you provide steps to recreate this? What were you doing that caused this error?

**Comment by leipzig** [comment]
run through instructions for a fresh install

```
./bin/manage.py runserver 0.0.0.0:8000
```

then attempt to access the web instance the server running it:
http://1.2.3.4:8000/

**Comment by naegelyd** [comment]
I'm confused. Varify-data-warehouse is not meant to be run as a server. If
you want all the resources and whatnot, checkout varify and run the server
in that app and it should all work out.

-Don

**Comment by leipzig** [comment]
ok, i thought I could check admin panel from vdw
